version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartattendance-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - MONGODB_URI=mongodb+srv://bekamayela18_db_user:2qBIVM2Qn3IZDAQy@cluster0.ifaywcg.mongodb.net/
      - MONGODB_DB_NAME=smart_attendance
    volumes:
      - ./backend/models:/app/models
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - smartattendance-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartattendance-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - smartattendance-network

networks:
  smartattendance-network:
    driver: bridge
